#!/bin/bash

echo "🔐 hCaptcha Setup Guide for SunShare Philippines"
echo "================================================="
echo ""

echo "1. Go to https://www.hcaptcha.com/"
echo "2. Click 'Sign Up' and create an account"
echo "3. After registration, go to https://dashboard.hcaptcha.com/sites"
echo "4. Click 'New Site'"
echo "5. Enter these details:"
echo "   - Site Name: SunShare Philippines"
echo "   - Hostnames: localhost, sunshareenergy.ph, sunshareenergyph.vercel.app"
echo "   - Site Type: Website"
echo ""
echo "6. After creating the site, copy your keys:"
echo "   - Site Key (public): Goes in NEXT_PUBLIC_HCAPTCHA_SITEKEY"
echo "   - Secret Key (private): Goes in HCAPTCHA_SECRET"
echo ""
echo "7. Update your .env.local file with the real keys"
echo "8. Also add these to Vercel environment variables"
echo ""
echo "Current test keys (development only):"
echo "NEXT_PUBLIC_HCAPTCHA_SITEKEY=10000000-ffff-ffff-ffff-000000000001"
echo "HCAPTCHA_SECRET=0x0000000000000000000000000000000000000000"
echo ""
echo "These test keys will work for local development but you need real keys for production."